name: CI Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  # Use Linux runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make all .sh scripts executable
        run: chmod +x hello.sh hello2.sh hello3.sh  # Make all scripts executable

      - name: Run hello.sh script
        run: ./hello.sh  # Run the first script

      - name: Run hello2.sh script
        run: ./hello2.sh  # Run the second script

      - name: Run hello3.sh script
        run: ./hello3.sh  # Run the third script

      - name: Step 1 - Generate Value
        id: step1  # Required to reference the output later
        run: |
          echo "my_output=$(date)" >> $GITHUB_OUTPUT

      - name: Step 2 - Use output from Step 1
        run: echo "The output from Step 1 is: ${{ steps.step1.outputs.my_output }}"
