name: CI Workflow

on: [push]

env:
  APP_NAME: MYAPP
  NODE_ENV: production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run hello.sh script with WSL
        run: |
          ./hello.sh
