name: CI Workflow

on: [push]

env:
  APP_NAME: MYAPP
  NODE_ENV: production

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Show APP_NAME
        run: echo "APP_NAME: $env:APP_NAME"

      - name: Show NODE_ENV
        run: echo "NODE_ENV: $env:NODE_ENV"
