name: CI Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  # Use Linux runner if you're using a .sh script

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run hello.sh script
        run: |
          ./hello.sh
