name: CI Workflow

on: [push]

env:
  APP_NAME: MYAPP
  NODE_ENV: production

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Show APP_NAME
        run: |
          echo "APP_NAME: $env:APP_NAME"

      - name: Show NODE_ENV
        run: |
          echo ${{ vars.MY_NAME }}
      - name: Show ENV_VAriable
        run : |
         echo ${{ secrets.USERNAME }}
      - name: Show EnvVAriables
        run: |
          ./hello.sh

  
