name: CI Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  # Use Linux runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make hello.sh executable
        run: chmod +x hello.sh  # Make the script executable

      - name: Run hello.sh script
        run: ./hello.sh  # Now it should work without permission errors
